name: Check

on:
  workflow_dispatch:
  merge_group:
  pull_request:
    branches: [ "main" ]
    types: [ opened, reopened, synchronize ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  checks: write
  pull-requests: write
  actions: read
  issues: read
  contents: read
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP and Composer
        uses: ./.github/actions/setup-php

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.testing', '.env');"

      - name: Generate key
        run: php artisan key:generate --env=testing

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

#      - name: Upgrade Chrome Driver
#        run: php artisan dusk:chrome-driver --detect
#
#      - name: Start Chrome Driver
#        run: ./vendor/laravel/dusk/bin/chromedriver-linux &

      - name: Install and Build npm
        run: |
          npm ci
          npm run build

      - name: Run Laravel Server
        run: php artisan serve &

      - name: Execute tests
        env:
          XDEBUG_MODE: coverage
        run: >
          vendor/bin/pest --ci
          --log-junit=junit-report.xml
          --coverage --coverage-clover coverage-report.xml --min=85
          --exclude-testsuite=Browser

      - name: Start Sail environment
        run: |
          ./vendor/bin/sail up -d

      - name: Execute Browser Tests
        run: >
          ./vendor/bin/sail dusk

      - name: Stop Sail environment
        run: |
          ./vendor/bin/sail down

      - name: Report Coverage in comment
        uses: lucassabreu/comment-coverage-clover@v0.13.0
        with:
          file: coverage-report.xml

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: tests/Browser/screenshots

      - name: Upload Console Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: console
          path: tests/Browser/console

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: ./junit-report.xml

  pint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP and Composer
        uses: ./.github/actions/setup-php
      - run: ./vendor/bin/pint
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: pint

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1

  conventional-commits:
    runs-on: ubuntu-latest
    if: github.event_name != 'merge_group'
    steps:
      - name: At least one conventional commit
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr view ${{ github.event.number }} \
          -R ${{ github.repository }} \
          --json title,commits --jq '.commits[].messageHeadline, .title' \
          | grep -E '(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([-a-zA-Z0-9]+\))?.+'

  phpstan-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP and Composer
        uses: ./.github/actions/setup-php

      - name: Run phpstan
        uses: paulschuberth/action-reviewdog-phpstan@main
        with:
          github_token: '${{ github.token }}'
          level: 'error'
          phpstan_level: 'max'
          fail_on_error: 'true'
          target_directory: 'app'

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name != 'merge_group'
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4

  automerge-dependabot:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_URL: ${{ github.event.pull_request.html_url }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Approve a PR if not already approved
        run: |
          gh pr checkout "$PR_URL" # sets the upstream metadata for `gh pr status`
          if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ];
          then gh pr review --approve "$PR_URL"
          else echo "PR already approved, skipping additional approvals to minimize emails/notification noise.";
          fi
      - name: Enable auto-merge
        run: gh pr merge --auto --merge "$PR_URL"